#! /usr/local/bin/node
var opts = process.argv.slice(2);
var fs = require('fs');
var data = require('./students');
var callon = require('./callon.js');

var caller = new callon(data, opts);

console.log(caller.run());
